# docker-compose-test.yml
version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tariffdb
    ports:
      - "5435:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: